services:
  postgres:
    container_name: "PC_builder_DB"
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=pcbuilder'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
